version: "3.5"
services:
  app:
    hostname: app
    container_name: app
    build:
      context: .
    image: webhookssh
    networks:
      - webhookssh
    expose:
      - 80
      - 443
    ports:
      - 5001:80
    restart: always
  redis:
    hostname: redis
    container_name: redis
    image: redis:alpine
    volumes:
      - ./.docker-compose/redis/data:/data
    networks:
      - webhookssh
    expose:
      - 6379
    restart: always
networks:
  webhookssh:
