version: "3.5"
services:
  webhookssh:
    hostname: webhookssh
    container_name: webhookssh
    build:
      context: .
    image: webhookssh
    networks:
      - webhookssh
    expose:
      - 8033
      - 4433
    ports:
      - 7002:4433
    restart: always
  redis:
    hostname: redis
    container_name: webhookssh_redis
    image: redis:alpine
    volumes:
      - ./.docker-compose/redis/data:/data
    networks:
      - webhookssh
    expose:
      - 6379
    ports:
      - 127.0.0.1:7501:6379
    restart: always
networks:
  webhookssh:
