version: "3"
services:
  app:
    build:
      context: .
    image: webhook-ssh
    expose:
      - 80
      - 443
    ports:
      - 5001:80
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - ./.docker-compose/redis/data:/data
    expose:
      - 6379
    restart: always
